#!/bin/bash

# 合同模板动态渲染系统 - 快速启动方案
# 由于网络下载问题，使用最简单的方式

echo "======================================"
echo "   快速启动方案（3种选择）"
echo "======================================"
echo ""

echo "方案1：使用IntelliJ IDEA（最推荐，最简单）"
echo "--------------------------------------"
echo "1. 打开 IntelliJ IDEA"
echo "2. File → Open → 选择目录："
echo "   /home/wula/IdeaProjects/dymic"
echo "3. 等待项目加载完成"
echo "4. 找到文件："
echo "   src/main/java/com/contract/ContractTemplateApplication.java"
echo "5. 右键点击 → Run 'ContractTemplateApplication'"
echo "6. 等待启动完成（显示 'Started ContractTemplateApplication'）"
echo "7. 打开浏览器访问："
echo "   http://localhost:8080/index.html"
echo ""

echo "方案2：安装Maven后启动（需要sudo权限）"
echo "--------------------------------------"
echo "在终端执行："
echo "  sudo apt-get update"
echo "  sudo apt-get install -y maven"
echo "  cd /home/wula/IdeaProjects/dymic"
echo "  mvn clean spring-boot:run"
echo "  打开浏览器: http://localhost:8080/index.html"
echo ""

echo "方案3：使用SDKMAN安装Maven（无需sudo）"
echo "--------------------------------------"
echo "在终端执行："
echo "  curl -s 'https://get.sdkman.io' | bash"
echo "  source ~/.sdkman/bin/sdkman-init.sh"
echo "  sdk install maven"
echo "  cd /home/wula/IdeaProjects/dymic"
echo "  mvn spring-boot:run"
echo "  打开浏览器: http://localhost:8080/index.html"
echo ""

echo "======================================"
echo "   启动成功后访问地址"
echo "======================================"
echo "✓ 入口页面: http://localhost:8080/index.html"
echo "✓ 简单界面: http://localhost:8080/simple.html"
echo "✓ 复杂界面: http://localhost:8080/complex.html"
echo "✓ H2控制台: http://localhost:8080/h2-console"
echo "======================================"
echo ""

echo "提示："
echo "  - 首次启动需要下载依赖，可能需要5-10分钟"
echo "  - 如果8080端口被占用，修改application.yml中的server.port"
echo "  - H2控制台登录：JDBC URL=jdbc:h2:mem:testdb, User=sa, Password=(空)"
echo ""