spring:
  application:
    name: contract-template

  datasource:
    url: jdbc:postgresql://localhost:5432/contract_template?options=-c%20TimeZone=UTC
    driver-class-name: org.postgresql.Driver
    username: gaussdb
    password: OpenGauss@123

  sql:
    init:
      mode: never  # openGauss 手动初始化

  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false

mybatis:
  mapper-locations: classpath:mapper/*.opengauss.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8888

logging:
  level:
    com.contract: DEBUG
